// Generated by CoffeeScript 1.7.1
(function() {
  var generateUniqueId, id;

  id = 1000;

  generateUniqueId = function() {
    return id++;
  };

  module.exports = generateUniqueId;

}).call(this);
